CREATE EXTENSION IF NOT EXISTS pg_bigm;

CREATE TABLE site_settings (
  key text PRIMARY KEY,
  value jsonb NOT NULL,
  version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE novel_sources (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL,
  name text NOT NULL,
  relative_path text NOT NULL UNIQUE,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT novel_sources_slug_nonempty CHECK (btrim(slug) <> '')
);
CREATE UNIQUE INDEX novel_sources_slug_unique ON novel_sources (lower(slug));

CREATE TABLE novels (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  title_search_original text NOT NULL,
  title_search_hans text,
  normalization_version integer NOT NULL,
  description text NOT NULL DEFAULT '',
  file_name text NOT NULL,
  relative_path text NOT NULL UNIQUE,
  source_id integer REFERENCES novel_sources(id) ON DELETE SET NULL,
  storage_mode text NOT NULL DEFAULT 'single' CHECK (storage_mode IN ('single', 'chapters')),
  chapter_count integer NOT NULL DEFAULT 0 CHECK (chapter_count >= 0),
  access_mode text NOT NULL DEFAULT 'inherit' CHECK (access_mode IN ('inherit', 'soda')),
  soda_price integer NOT NULL DEFAULT 0 CHECK (soda_price >= 0),
  preview_chapter_count integer NOT NULL DEFAULT 0 CHECK (preview_chapter_count >= 0),
  content_hash text,
  published_content_version text,
  size_bytes bigint NOT NULL DEFAULT 0 CHECK (size_bytes >= 0),
  mtime_ms bigint NOT NULL DEFAULT 0 CHECK (mtime_ms >= 0),
  word_count integer NOT NULL DEFAULT 0 CHECK (word_count >= 0),
  visit_count bigint NOT NULL DEFAULT 0 CHECK (visit_count >= 0),
  recommend_count bigint NOT NULL DEFAULT 0 CHECK (recommend_count >= 0),
  last_accessed_at timestamptz,
  last_accessed_ip inet,
  last_accessed_user_agent text,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT novels_title_nonempty CHECK (btrim(title) <> '')
);
CREATE INDEX novels_title_search_original_idx ON novels USING gin (title_search_original gin_bigm_ops) WITH (fastupdate = off);
CREATE INDEX novels_title_search_hans_idx ON novels USING gin (title_search_hans gin_bigm_ops) WITH (fastupdate = off) WHERE title_search_hans IS NOT NULL;
CREATE INDEX novels_updated_idx ON novels (mtime_ms DESC, id DESC);
CREATE INDEX novels_words_idx ON novels (word_count DESC, id DESC);
CREATE INDEX novels_source_updated_idx ON novels (source_id, mtime_ms DESC, id DESC);
CREATE INDEX novels_source_words_idx ON novels (source_id, word_count DESC, id DESC);

CREATE TABLE novel_chapters (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  novel_id integer NOT NULL REFERENCES novels(id) ON DELETE CASCADE,
  title text NOT NULL,
  title_override text,
  relative_path text NOT NULL UNIQUE,
  sort_order integer NOT NULL DEFAULT 0,
  sort_override integer,
  content_hash text,
  published_content_version text,
  size_bytes bigint NOT NULL DEFAULT 0 CHECK (size_bytes >= 0),
  mtime_ms bigint NOT NULL DEFAULT 0 CHECK (mtime_ms >= 0),
  word_count integer NOT NULL DEFAULT 0 CHECK (word_count >= 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (novel_id, sort_order)
);
CREATE INDEX novel_chapters_novel_sort_idx ON novel_chapters (novel_id, sort_order, id);

CREATE TABLE novel_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  novel_id integer NOT NULL REFERENCES novels(id) ON DELETE CASCADE,
  chapter_id integer REFERENCES novel_chapters(id) ON DELETE CASCADE,
  active_generation integer NOT NULL DEFAULT 0 CHECK (active_generation >= 0),
  active_content_version text,
  staging_generation integer CHECK (staging_generation > 0),
  staging_content_version text,
  normalization_version integer NOT NULL DEFAULT 0 CHECK (normalization_version >= 0),
  state text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'building', 'ready', 'failed')),
  last_error text,
  indexed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE NULLS NOT DISTINCT (novel_id, chapter_id)
);
CREATE INDEX novel_documents_active_idx ON novel_documents (novel_id, chapter_id, active_generation, active_content_version);

CREATE TABLE novel_content_blocks (
  document_id bigint NOT NULL REFERENCES novel_documents(id) ON DELETE CASCADE,
  generation integer NOT NULL CHECK (generation > 0),
  block_no integer NOT NULL CHECK (block_no >= 0),
  char_start integer NOT NULL CHECK (char_start >= 0),
  char_end integer NOT NULL CHECK (char_end > char_start),
  search_window_start integer NOT NULL CHECK (search_window_start >= 0),
  search_window_end integer NOT NULL CHECK (search_window_end >= char_end),
  original_text text NOT NULL,
  search_source_text text NOT NULL,
  search_text_original text NOT NULL,
  search_text_hans text,
  PRIMARY KEY (document_id, generation, block_no),
  CHECK (search_window_start <= char_start),
  CHECK (btrim(original_text) <> '')
);
CREATE INDEX novel_content_blocks_original_idx ON novel_content_blocks USING gin (search_text_original gin_bigm_ops) WITH (fastupdate = off);
CREATE INDEX novel_content_blocks_hans_idx ON novel_content_blocks USING gin (search_text_hans gin_bigm_ops) WITH (fastupdate = off) WHERE search_text_hans IS NOT NULL;

CREATE TABLE content_jobs (
  id uuid PRIMARY KEY,
  kind text NOT NULL CHECK (kind IN ('content-import', 'search-index', 'media-prepare', 'outbox-dispatch')),
  dedupe_key text NOT NULL,
  payload jsonb NOT NULL,
  status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'done', 'failed', 'cancelled')),
  priority smallint NOT NULL DEFAULT 0,
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  available_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  lease_owner text,
  lease_expires_at timestamptz,
  progress jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE UNIQUE INDEX content_jobs_active_dedupe_idx
  ON content_jobs (kind, dedupe_key)
  WHERE status IN ('queued', 'running');
CREATE INDEX content_jobs_ready_idx
  ON content_jobs (priority DESC, available_at, created_at, id)
  WHERE status = 'queued';

