-- Business domains imported from the final SQLite schema, with explicit PostgreSQL types.
-- IDs, password/token hashes and encrypted delivery material are preserved on import.
-- Date-only business keys retain their existing Asia/Shanghai calendar semantics.
-- IP audit strings intentionally remain text: legacy data may contain non-address labels.
-- Foreign keys are deferred so parent-tag links and batched imports remain atomic.

CREATE TABLE admin_login_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL,
  ip text NOT NULL,
  user_agent text NOT NULL DEFAULT '',
  logged_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE admin_user_anonymization_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  previous_username text NOT NULL,
  actor text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  audience text NOT NULL DEFAULT 'public' CHECK(audience IN ('public', 'member')),
  importance text NOT NULL DEFAULT 'normal' CHECK(importance IN ('normal', 'important')),
  display_mode text NOT NULL DEFAULT 'list' CHECK(display_mode IN ('list', 'drawer', 'both')),
  entry_version text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft', 'published', 'archived')),
  published_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE app_metadata (
  key text PRIMARY KEY,
  value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE background_leases (
  name text PRIMARY KEY,
  holder_id text NOT NULL,
  expires_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE content_access_policies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  scope text NOT NULL DEFAULT 'all' CHECK(scope IN ('all', 'novel', 'video', 'audio', 'file')),
  country_mode text NOT NULL DEFAULT 'all' CHECK(country_mode IN ('all', 'cn', 'non_cn')),
  audience text NOT NULL DEFAULT 'guest' CHECK(audience IN ('all', 'guest')),
  window_seconds integer NOT NULL,
  max_requests integer NOT NULL,
  block_seconds integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE content_access_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type text NOT NULL CHECK(target_type IN ('ip', 'cidr', 'country', 'crawler')),
  target_value text NOT NULL,
  match_mode text NOT NULL DEFAULT 'include' CHECK(match_mode IN ('include', 'exclude')),
  scope text NOT NULL DEFAULT 'all' CHECK(scope IN ('all', 'novel', 'video', 'audio', 'file')),
  country_mode text NOT NULL DEFAULT 'all' CHECK(country_mode IN ('all', 'cn', 'non_cn')),
  audience text NOT NULL DEFAULT 'all' CHECK(audience IN ('all', 'guest')),
  source text NOT NULL DEFAULT 'manual' CHECK(source IN ('manual', 'rate_limit')),
  reason text NOT NULL DEFAULT '',
  expires_at timestamptz,
  enabled boolean NOT NULL DEFAULT true,
  created_by text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE domain_revisions (
  domain text PRIMARY KEY,
  revision bigint NOT NULL DEFAULT 0 CHECK(revision >= 0),
  updated_at timestamptz NOT NULL DEFAULT '1970-01-01T00:00:00Z'::timestamptz
);

CREATE TABLE email_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dedupe_key text NOT NULL UNIQUE,
  recipient text NOT NULL,
  template text NOT NULL,
  payload_json jsonb NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'sending', 'sent', 'failed')),
  attempts integer NOT NULL DEFAULT 0 CHECK(attempts >= 0),
  next_attempt_at timestamptz NOT NULL DEFAULT '1970-01-01T00:00:00Z'::timestamptz,
  last_error text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE engagement_events (
  event_id text PRIMARY KEY,
  viewer_key text NOT NULL,
  content_type text NOT NULL CHECK(content_type IN ('novel', 'original', 'video', 'audio', 'file')),
  content_id bigint NOT NULL,
  action text NOT NULL CHECK(action IN ('detail_view', 'read_open', 'play_start')),
  counted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL
);

CREATE TABLE market_products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft', 'published', 'archived')),
  min_level integer NOT NULL DEFAULT 1 CHECK(min_level BETWEEN 1 AND 6),
  price_cookie bigint CHECK(price_cookie IS NULL OR price_cookie >= 0),
  price_soda bigint CHECK(price_soda IS NULL OR price_soda >= 0),
  purchase_limit_per_user integer NOT NULL DEFAULT 1 CHECK(purchase_limit_per_user >= 0),
  sort_order integer NOT NULL DEFAULT 0,
  cover_key text,
  cover_storage_node_id text,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE market_assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL,
  storage_node_id text,
  file_name text NOT NULL,
  stored_name text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream',
  size_bytes bigint NOT NULL CHECK(size_bytes > 0),
  mtime_ms bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE(storage_node_id, stored_name),
  FOREIGN KEY(product_id) REFERENCES market_products(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE market_delivery_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL,
  kind text NOT NULL CHECK(kind IN ('text', 'secret', 'file', 'entitlement')),
  title text NOT NULL DEFAULT '',
  content text NOT NULL DEFAULT '',
  market_asset_id bigint,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(product_id) REFERENCES market_products(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(market_asset_id) REFERENCES market_assets(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE market_secret_inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL,
  ciphertext text NOT NULL,
  iv text NOT NULL,
  auth_tag text NOT NULL,
  status text NOT NULL DEFAULT 'available' CHECK(status IN ('available', 'delivered', 'disabled')),
  order_id bigint,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  delivered_at timestamptz,
  FOREIGN KEY(product_id) REFERENCES market_products(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE mutation_receipts (
  mutation_id text PRIMARY KEY,
  user_id bigint,
  operation text NOT NULL,
  target_key text NOT NULL DEFAULT '',
  payload_hash text NOT NULL DEFAULT '',
  result_json jsonb NOT NULL,
  created_at timestamptz NOT NULL
);

CREATE TABLE novel_hotwords (
  novel_id integer NOT NULL,
  term text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(novel_id, term),
  FOREIGN KEY(novel_id) REFERENCES novels(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE novel_read_daily_stats (
  day date NOT NULL,
  novel_id integer NOT NULL,
  open_count bigint NOT NULL DEFAULT 0 CHECK(open_count >= 0),
  resume_count bigint NOT NULL DEFAULT 0 CHECK(resume_count >= 0),
  completion_count bigint NOT NULL DEFAULT 0 CHECK(completion_count >= 0),
  progress_sample_count bigint NOT NULL DEFAULT 0 CHECK(progress_sample_count >= 0),
  progress_percent_sum double precision NOT NULL DEFAULT 0 CHECK(progress_percent_sum >= 0),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(day, novel_id),
  FOREIGN KEY(novel_id) REFERENCES novels(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE novel_recommendation_pool (
  novel_id integer PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(novel_id) REFERENCES novels(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE pinned_novels (
  novel_id integer PRIMARY KEY,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(novel_id) REFERENCES novels(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE redemption_code_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  reward_type text NOT NULL CHECK(reward_type IN ('cookie', 'soda', 'product')),
  reward_amount bigint NOT NULL DEFAULT 0 CHECK(reward_amount >= 0),
  product_id bigint,
  status text NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'disabled')),
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(product_id) REFERENCES market_products(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE registration_invites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code_hash text NOT NULL UNIQUE,
  code_hint text NOT NULL,
  label text NOT NULL DEFAULT '',
  max_uses integer NOT NULL DEFAULT 1 CHECK(max_uses > 0),
  used_count bigint NOT NULL DEFAULT 0 CHECK(used_count >= 0),
  enabled boolean NOT NULL DEFAULT true,
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id bigint REFERENCES tags(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text NOT NULL DEFAULT '',
  aliases jsonb NOT NULL DEFAULT '[]'::jsonb,
  sort_order integer NOT NULL DEFAULT 0,
  visibility text NOT NULL DEFAULT 'public' CHECK(visibility IN ('public', 'member', 'hidden')),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE novel_tags (
  novel_id integer NOT NULL,
  tag_id bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(novel_id, tag_id),
  FOREIGN KEY(novel_id) REFERENCES novels(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE telegram_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dedupe_key text UNIQUE,
  method text NOT NULL,
  payload_json jsonb NOT NULL,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'sent', 'failed')),
  attempts integer NOT NULL DEFAULT 0,
  next_attempt_at timestamptz NOT NULL,
  last_error text NOT NULL DEFAULT '',
  sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE telegram_updates (
  update_id bigint PRIMARY KEY,
  processed_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE user_levels (
  level integer PRIMARY KEY CHECK(level BETWEEN 0 AND 6),
  name text NOT NULL,
  soda_required bigint NOT NULL DEFAULT 0 CHECK(soda_required >= 0),
  daily_video_download_limit integer NOT NULL DEFAULT 3 CHECK(daily_video_download_limit BETWEEN 0 AND 1000),
  permissions jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  video_concurrency_limit integer NOT NULL DEFAULT 1 CHECK(video_concurrency_limit BETWEEN 0 AND 20)
);

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  display_name text NOT NULL,
  password_hash text NOT NULL,
  avatar_path text,
  status text NOT NULL DEFAULT 'active',
  role text NOT NULL DEFAULT 'user' CHECK(role IN ('user', 'admin')),
  trust_level integer NOT NULL DEFAULT 1 CHECK(trust_level BETWEEN 0 AND 6),
  soda_balance bigint NOT NULL DEFAULT 0 CHECK(soda_balance >= 0),
  soda_experience bigint NOT NULL DEFAULT 0 CHECK(soda_experience >= 0),
  search_rate_limit_per_minute integer,
  locale_preference text NOT NULL DEFAULT 'zh-Hans' CHECK(locale_preference IN ('zh-Hans', 'zh-Hant')),
  reading_history_enabled boolean NOT NULL DEFAULT true,
  original_reading_history_enabled boolean NOT NULL DEFAULT true,
  reading_progress_enabled boolean NOT NULL DEFAULT true,
  registration_ip text,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  last_login_at timestamptz,
  last_login_ip text,
  email text,
  email_verified_at timestamptz,
  cookie_balance bigint NOT NULL DEFAULT 0 CHECK(cookie_balance >= 0),
  deleted_at timestamptz
);

CREATE TABLE announcement_reads (
  announcement_id bigint NOT NULL,
  user_id bigint NOT NULL,
  read_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(announcement_id, user_id),
  FOREIGN KEY(announcement_id) REFERENCES announcements(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE email_verification_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE market_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no text NOT NULL UNIQUE,
  user_id bigint NOT NULL,
  product_id bigint,
  product_title text NOT NULL,
  currency text NOT NULL CHECK(currency IN ('soda', 'cookie')),
  amount bigint NOT NULL CHECK(amount >= 0),
  status text NOT NULL DEFAULT 'paid' CHECK(status IN ('paid', 'fulfilled', 'cancelled', 'refunded')),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  fulfilled_at timestamptz,
  admin_deleted_at timestamptz,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(product_id) REFERENCES market_products(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE market_order_deliveries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL,
  kind text NOT NULL CHECK(kind IN ('text', 'secret', 'file', 'entitlement')),
  title text NOT NULL DEFAULT '',
  content text NOT NULL DEFAULT '',
  market_asset_id bigint,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(order_id) REFERENCES market_orders(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(market_asset_id) REFERENCES market_assets(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE novel_recommendations (
  novel_id integer NOT NULL,
  user_id bigint NOT NULL,
  soda_spent bigint NOT NULL DEFAULT 0 CHECK(soda_spent >= 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(novel_id, user_id),
  FOREIGN KEY(novel_id) REFERENCES novels(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE original_articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL,
  author_id bigint NOT NULL,
  title text NOT NULL,
  excerpt text NOT NULL DEFAULT '',
  body_markdown text NOT NULL,
  paid_body_markdown text NOT NULL DEFAULT '',
  word_count bigint NOT NULL DEFAULT 0 CHECK(word_count >= 0),
  access_mode text NOT NULL DEFAULT 'free' CHECK(access_mode IN ('free', 'paid')),
  unlock_soda_price bigint NOT NULL DEFAULT 0 CHECK(unlock_soda_price >= 0),
  status text NOT NULL DEFAULT 'published' CHECK(status IN ('draft', 'published', 'hidden')),
  is_pinned boolean NOT NULL DEFAULT false,
  pinned_at timestamptz,
  view_count bigint NOT NULL DEFAULT 0 CHECK(view_count >= 0),
  comment_count bigint NOT NULL DEFAULT 0 CHECK(comment_count >= 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  published_at timestamptz,
  FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE original_article_drafts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id bigint,
  author_id bigint NOT NULL,
  client_key text NOT NULL,
  title text NOT NULL DEFAULT '',
  editor_state_json text NOT NULL DEFAULT '',
  legacy_public_markdown text NOT NULL DEFAULT '',
  legacy_paid_markdown text NOT NULL DEFAULT '',
  tags_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  unlock_soda_price bigint NOT NULL DEFAULT 0 CHECK(unlock_soda_price >= 0),
  revision bigint NOT NULL DEFAULT 1 CHECK(revision >= 1),
  content_hash text NOT NULL DEFAULT '',
  autosaved_at timestamptz NOT NULL,
  published_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  UNIQUE(author_id, client_key),
  FOREIGN KEY(article_id) REFERENCES original_articles(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE original_article_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id bigint NOT NULL,
  revision_no bigint NOT NULL,
  title text NOT NULL,
  body_markdown text NOT NULL,
  paid_body_markdown text NOT NULL DEFAULT '',
  outline_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  editor_state_json text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL,
  UNIQUE(article_id, revision_no),
  FOREIGN KEY(article_id) REFERENCES original_articles(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE original_assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id bigint NOT NULL,
  article_id bigint,
  file_name text NOT NULL,
  storage_path text NOT NULL UNIQUE,
  mime_type text NOT NULL,
  width integer NOT NULL CHECK(width > 0),
  height integer NOT NULL CHECK(height > 0),
  size_bytes bigint NOT NULL CHECK(size_bytes > 0),
  alt_text text NOT NULL DEFAULT '',
  caption text NOT NULL DEFAULT '',
  access_scope text NOT NULL DEFAULT 'draft' CHECK(access_scope IN ('draft', 'public', 'paid')),
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(article_id) REFERENCES original_articles(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE original_comment_daily_usage (
  user_id bigint NOT NULL,
  usage_date date NOT NULL,
  used_count bigint NOT NULL DEFAULT 0 CHECK(used_count >= 0),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(user_id, usage_date),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE original_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id bigint NOT NULL,
  author_id bigint NOT NULL,
  body_markdown text NOT NULL,
  status text NOT NULL DEFAULT 'published' CHECK(status IN ('published', 'hidden')),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(article_id) REFERENCES original_articles(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE original_purchases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id bigint NOT NULL,
  buyer_id bigint NOT NULL,
  author_id bigint NOT NULL,
  price_soda bigint NOT NULL CHECK(price_soda > 0),
  reference_key text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE(article_id, buyer_id),
  FOREIGN KEY(article_id) REFERENCES original_articles(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(buyer_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE original_reading_history (
  user_id bigint NOT NULL,
  article_id bigint NOT NULL,
  visit_count bigint NOT NULL DEFAULT 0 CHECK(visit_count >= 0),
  scroll_ratio double precision NOT NULL DEFAULT 0 CHECK(scroll_ratio >= 0 AND scroll_ratio <= 1),
  progress_percent double precision NOT NULL DEFAULT 0 CHECK(progress_percent >= 0 AND progress_percent <= 100),
  completed boolean NOT NULL DEFAULT false,
  recorded_in_history boolean NOT NULL DEFAULT true,
  last_read_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(user_id, article_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(article_id) REFERENCES original_articles(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE original_tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL,
  name text NOT NULL,
  created_by integer REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE original_article_tags (
  article_id bigint NOT NULL,
  tag_id bigint NOT NULL,
  PRIMARY KEY(article_id, tag_id),
  FOREIGN KEY(article_id) REFERENCES original_articles(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(tag_id) REFERENCES original_tags(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE redemption_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id bigint NOT NULL,
  code_hash text NOT NULL UNIQUE,
  code_hint text NOT NULL,
  status text NOT NULL DEFAULT 'available' CHECK(status IN ('available', 'redeemed', 'disabled')),
  redeemed_by integer,
  redeemed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(batch_id) REFERENCES redemption_code_batches(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(redeemed_by) REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE search_query_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key text UNIQUE,
  query text NOT NULL,
  mode text NOT NULL CHECK(mode IN ('title', 'content')),
  source text NOT NULL DEFAULT 'direct',
  user_id bigint,
  origin_novel_id integer,
  result_count bigint,
  result_novel_count bigint,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(origin_novel_id) REFERENCES novels(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE search_query_terms (
  search_event_id bigint NOT NULL,
  term text NOT NULL,
  position integer NOT NULL DEFAULT 0,
  PRIMARY KEY(search_event_id, position),
  FOREIGN KEY(search_event_id) REFERENCES search_query_events(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE search_result_clicks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  search_event_id bigint NOT NULL,
  novel_id integer NOT NULL,
  segment_index integer,
  clicked_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(search_event_id) REFERENCES search_query_events(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(novel_id) REFERENCES novels(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE station_threads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  subject text NOT NULL,
  status text NOT NULL DEFAULT 'open' CHECK(status IN ('open', 'closed')),
  user_last_read_message_id bigint NOT NULL DEFAULT 0,
  admin_last_read_message_id bigint NOT NULL DEFAULT 0,
  last_message_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE station_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id bigint NOT NULL,
  author_role text NOT NULL CHECK(author_role IN ('user', 'admin')),
  author_user_id bigint,
  body text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(thread_id) REFERENCES station_threads(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(author_user_id) REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE telegram_link_tokens (
  token_hash text PRIMARY KEY,
  user_id bigint NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE telegram_message_links (
  chat_id text NOT NULL,
  message_id bigint NOT NULL,
  station_thread_id bigint NOT NULL,
  station_message_id bigint,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(chat_id, message_id),
  FOREIGN KEY(station_thread_id) REFERENCES station_threads(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(station_message_id) REFERENCES station_messages(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE telegram_user_links (
  user_id bigint PRIMARY KEY,
  chat_id text NOT NULL UNIQUE,
  telegram_username text NOT NULL DEFAULT '',
  linked_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_checkins (
  user_id bigint NOT NULL,
  checkin_date date NOT NULL,
  reward bigint NOT NULL CHECK(reward BETWEEN 1 AND 20),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(user_id, checkin_date),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_currency_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  currency text NOT NULL CHECK(currency IN ('soda', 'cookie')),
  amount bigint NOT NULL,
  balance_after bigint NOT NULL CHECK(balance_after >= 0),
  source text NOT NULL,
  reference_key text,
  note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_entitlements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  resource_type text NOT NULL,
  resource_id text NOT NULL,
  rights jsonb NOT NULL DEFAULT '[]'::jsonb,
  source_order_id bigint,
  granted_by text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  expires_at timestamptz,
  UNIQUE(user_id, resource_type, resource_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(source_order_id) REFERENCES market_orders(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_hidden_tags (
  user_id bigint NOT NULL,
  tag_id bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(user_id, tag_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_login_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint,
  username text NOT NULL,
  ip text NOT NULL,
  user_agent text NOT NULL DEFAULT '',
  logged_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_novel_favorites (
  user_id bigint NOT NULL,
  novel_id integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(user_id, novel_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(novel_id) REFERENCES novels(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_novel_grove (
  user_id bigint NOT NULL,
  novel_id integer NOT NULL,
  visit_count bigint NOT NULL DEFAULT 0 CHECK(visit_count >= 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(user_id, novel_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(novel_id) REFERENCES novels(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_original_author_blocks (
  user_id bigint NOT NULL,
  author_id bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(user_id, author_id),
  CHECK(user_id <> author_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_original_favorites (
  user_id bigint NOT NULL,
  article_id bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(user_id, article_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(article_id) REFERENCES original_articles(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_original_grove (
  user_id bigint NOT NULL,
  article_id bigint NOT NULL,
  visit_count bigint NOT NULL DEFAULT 0 CHECK(visit_count >= 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(user_id, article_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(article_id) REFERENCES original_articles(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_read_daily_stats (
  day date NOT NULL,
  user_id bigint NOT NULL,
  open_count bigint NOT NULL DEFAULT 0 CHECK(open_count >= 0),
  resume_count bigint NOT NULL DEFAULT 0 CHECK(resume_count >= 0),
  completion_count bigint NOT NULL DEFAULT 0 CHECK(completion_count >= 0),
  progress_update_count bigint NOT NULL DEFAULT 0 CHECK(progress_update_count >= 0),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(day, user_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_reading_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  novel_id integer NOT NULL,
  chapter_id integer,
  title text NOT NULL,
  segment_index integer NOT NULL DEFAULT 0,
  segment_ratio double precision NOT NULL DEFAULT 0 CHECK(segment_ratio >= 0 AND segment_ratio <= 1),
  progress_percent double precision NOT NULL DEFAULT 0 CHECK(progress_percent >= 0 AND progress_percent <= 100),
  content_version text NOT NULL DEFAULT '',
  completed boolean NOT NULL DEFAULT false,
  recorded_in_history boolean NOT NULL DEFAULT true,
  visit_count bigint NOT NULL DEFAULT 0,
  last_read_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE(user_id, novel_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(novel_id) REFERENCES novels(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(chapter_id) REFERENCES novel_chapters(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_sessions (
  id text PRIMARY KEY,
  user_id bigint NOT NULL,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  last_seen_at timestamptz,
  last_ip text,
  user_agent text,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_soda_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  amount bigint NOT NULL,
  balance_after bigint NOT NULL CHECK(balance_after >= 0),
  source text NOT NULL,
  note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE video_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_visible boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE media_assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL CHECK(kind IN ('video', 'audio', 'file')),
  storage_node_id text,
  category_id bigint REFERENCES video_categories(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
  title text NOT NULL,
  artist text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  file_name text NOT NULL,
  stored_name text NOT NULL UNIQUE,
  mime_type text NOT NULL,
  size_bytes bigint NOT NULL,
  mtime_ms bigint NOT NULL DEFAULT 0,
  duration_seconds double precision,
  thumbnail_version bigint NOT NULL DEFAULT 0,
  custom_cover_key text,
  playback_format text NOT NULL DEFAULT 'mp4' CHECK(playback_format IN ('mp4', 'hls')),
  playback_version text NOT NULL DEFAULT '',
  playback_manifest_path text,
  playback_status text NOT NULL DEFAULT 'none' CHECK(playback_status IN ('none', 'pending', 'processing', 'ready', 'failed')),
  playback_error text NOT NULL DEFAULT '',
  playback_published_at timestamptz,
  play_count bigint NOT NULL DEFAULT 0,
  recommend_count bigint NOT NULL DEFAULT 0 CHECK(recommend_count >= 0),
  download_count bigint NOT NULL DEFAULT 0,
  published_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  content_updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  new_until timestamptz,
  play_soda_price bigint NOT NULL DEFAULT 0 CHECK(play_soda_price >= 0),
  download_soda_price bigint NOT NULL DEFAULT 1 CHECK(download_soda_price >= 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE analytics_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint,
  event_type text NOT NULL,
  path text NOT NULL,
  referrer text,
  ip text NOT NULL,
  country text,
  user_agent text NOT NULL DEFAULT '',
  device text NOT NULL DEFAULT 'unknown',
  browser text NOT NULL DEFAULT 'unknown',
  os text NOT NULL DEFAULT 'unknown',
  novel_id integer,
  media_id bigint,
  tag_id bigint,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(novel_id) REFERENCES novels(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(media_id) REFERENCES media_assets(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE content_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  novel_id integer,
  media_id bigint,
  original_article_id bigint,
  category text NOT NULL CHECK(category IN ('title_error', 'tag_error', 'hotword_error', 'playback_error', 'spam', 'other')),
  details text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'open' CHECK(status IN ('open', 'resolved')),
  resolved_by text,
  resolved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK(
        (novel_id IS NOT NULL AND media_id IS NULL AND original_article_id IS NULL) OR
        (novel_id IS NULL AND media_id IS NOT NULL AND original_article_id IS NULL) OR
        (novel_id IS NULL AND media_id IS NULL AND original_article_id IS NOT NULL)
      ),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(novel_id) REFERENCES novels(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(media_id) REFERENCES media_assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(original_article_id) REFERENCES original_articles(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE media_download_grants (
  user_id bigint NOT NULL,
  media_id bigint NOT NULL,
  soda_spent bigint NOT NULL DEFAULT 0 CHECK(soda_spent >= 0),
  granted_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(user_id, media_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(media_id) REFERENCES media_assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE media_download_sessions (
  token_hash text PRIMARY KEY,
  user_id bigint NOT NULL,
  media_id bigint NOT NULL,
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(media_id) REFERENCES media_assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE media_playback_grants (
  user_id bigint NOT NULL,
  media_id bigint NOT NULL,
  soda_spent bigint NOT NULL DEFAULT 0 CHECK(soda_spent >= 0),
  granted_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(user_id, media_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(media_id) REFERENCES media_assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE media_playback_jobs (
  media_id bigint PRIMARY KEY,
  source_version text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'processing', 'failed')),
  attempts integer NOT NULL DEFAULT 0 CHECK(attempts >= 0),
  last_error text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(media_id) REFERENCES media_assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE media_prepare_jobs (
  media_id bigint PRIMARY KEY,
  source_version bigint NOT NULL,
  thumbnail_percent integer NOT NULL DEFAULT 33,
  status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'processing', 'failed')),
  attempts integer NOT NULL DEFAULT 0 CHECK(attempts >= 0),
  next_run_at timestamptz NOT NULL DEFAULT '1970-01-01T00:00:00Z'::timestamptz,
  locked_until timestamptz,
  last_error text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY(media_id) REFERENCES media_assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE media_recommendations (
  media_id bigint NOT NULL,
  user_id bigint NOT NULL,
  soda_spent bigint NOT NULL DEFAULT 1 CHECK(soda_spent > 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(media_id, user_id),
  FOREIGN KEY(media_id) REFERENCES media_assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_media_favorites (
  user_id bigint NOT NULL,
  media_id bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(user_id, media_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(media_id) REFERENCES media_assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_media_grove (
  user_id bigint NOT NULL,
  media_id bigint NOT NULL,
  visit_count bigint NOT NULL DEFAULT 0 CHECK(visit_count >= 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(user_id, media_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(media_id) REFERENCES media_assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE user_media_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  media_id bigint NOT NULL,
  kind text NOT NULL CHECK(kind IN ('video', 'audio', 'file')),
  title text NOT NULL,
  visit_count bigint NOT NULL DEFAULT 0,
  last_accessed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE(user_id, media_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(media_id) REFERENCES media_assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE video_playback_sessions (
  id text PRIMARY KEY,
  viewer_key text NOT NULL,
  user_id bigint,
  client_id text NOT NULL,
  media_id bigint NOT NULL,
  storage_node_id text,
  reserved_kbps integer NOT NULL DEFAULT 0 CHECK(reserved_kbps >= 0),
  token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE(viewer_key, client_id),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(media_id) REFERENCES media_assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE video_tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL,
  description text NOT NULL DEFAULT '',
  sort_order integer NOT NULL DEFAULT 0,
  is_visible boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE media_asset_tags (
  media_id bigint NOT NULL,
  tag_id bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(media_id, tag_id),
  FOREIGN KEY(media_id) REFERENCES media_assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(tag_id) REFERENCES video_tags(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

ALTER TABLE market_secret_inventory ADD CONSTRAINT market_secret_inventory_order_fk
  FOREIGN KEY (order_id) REFERENCES market_orders(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE mutation_receipts ADD CONSTRAINT mutation_receipts_user_fk
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

CREATE UNIQUE INDEX market_products_slug_case_unique ON market_products (lower(slug));
CREATE UNIQUE INDEX tags_name_case_unique ON tags (lower(name));
CREATE UNIQUE INDEX original_articles_slug_case_unique ON original_articles (lower(slug));
CREATE UNIQUE INDEX original_tags_slug_case_unique ON original_tags (lower(slug));
CREATE UNIQUE INDEX video_categories_name_case_unique ON video_categories (lower(name));
CREATE UNIQUE INDEX video_tags_name_case_unique ON video_tags (lower(name));
CREATE UNIQUE INDEX video_tags_slug_case_unique ON video_tags (lower(slug));

CREATE INDEX idx_admin_login_records_time ON admin_login_records(logged_at);
CREATE INDEX idx_admin_user_anonymization_user_time
      ON admin_user_anonymization_audit(user_id, created_at DESC);
CREATE INDEX idx_announcements_visible
      ON announcements(status, audience, importance, published_at, expires_at);
CREATE INDEX idx_announcements_entry_visible ON announcements(display_mode, status, audience, importance, published_at, expires_at);
CREATE INDEX idx_content_access_policies_enabled
      ON content_access_policies(enabled, scope, country_mode, audience);
CREATE INDEX idx_content_access_rules_match
      ON content_access_rules(enabled, scope, country_mode, audience, target_type, target_value);
CREATE INDEX idx_content_access_rules_expiry
      ON content_access_rules(expires_at);
CREATE INDEX idx_email_outbox_ready
      ON email_outbox(status, next_attempt_at, id);
CREATE INDEX idx_engagement_events_dedupe
      ON engagement_events(viewer_key, content_type, content_id, action, created_at DESC);
CREATE INDEX idx_engagement_events_created
      ON engagement_events(created_at);
CREATE INDEX idx_market_products_visible
      ON market_products(status, sort_order, updated_at DESC);
CREATE INDEX idx_market_assets_product
      ON market_assets(product_id, id);
CREATE INDEX idx_market_delivery_items_product
      ON market_delivery_items(product_id, sort_order, id);
CREATE INDEX idx_market_secret_inventory_available
      ON market_secret_inventory(product_id, status, id);
CREATE INDEX idx_mutation_receipts_user_operation_time
      ON mutation_receipts(user_id, operation, created_at DESC);
CREATE INDEX idx_mutation_receipts_user_operation_target_time
      ON mutation_receipts(user_id, operation, target_key, created_at DESC);
CREATE INDEX idx_novel_hotwords_novel_sort ON novel_hotwords(novel_id, sort_order, term);
CREATE INDEX idx_novel_read_daily_day
      ON novel_read_daily_stats(day DESC, open_count DESC);
CREATE INDEX idx_pinned_novels_sort ON pinned_novels(sort_order, novel_id);
CREATE INDEX idx_tags_visibility_sort ON tags(visibility, sort_order, name);
CREATE INDEX idx_novel_tags_tag ON novel_tags(tag_id, novel_id);
CREATE INDEX idx_telegram_outbox_pending
      ON telegram_outbox(status, next_attempt_at, id);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_last_login ON users(last_login_at);
CREATE UNIQUE INDEX idx_users_email_unique
      ON users(lower(email))
      WHERE email IS NOT NULL AND email <> '';
CREATE INDEX idx_users_registration_ip_created ON users(registration_ip, created_at);
CREATE INDEX idx_users_role ON users(role, status);
CREATE INDEX idx_users_trust_level ON users(trust_level, status);
CREATE INDEX idx_email_verification_tokens_user
      ON email_verification_tokens(user_id, created_at DESC);
CREATE INDEX idx_email_verification_tokens_expiry
      ON email_verification_tokens(expires_at);
CREATE INDEX idx_market_orders_user_time
      ON market_orders(user_id, created_at DESC, id DESC);
CREATE INDEX idx_market_orders_status_time
      ON market_orders(status, created_at DESC, id DESC);
CREATE INDEX idx_market_order_deliveries_order
      ON market_order_deliveries(order_id, sort_order, id);
CREATE INDEX idx_novel_recommendations_novel_time
      ON novel_recommendations(novel_id, created_at DESC);
CREATE INDEX idx_original_articles_visible_time
      ON original_articles(status, published_at DESC, id DESC);
CREATE INDEX idx_original_articles_author_time
      ON original_articles(author_id, created_at DESC, id DESC);
CREATE INDEX idx_original_articles_author_visible_time
      ON original_articles(author_id, status, published_at DESC, id DESC);
CREATE INDEX idx_original_articles_title
      ON original_articles(lower(title), id);
CREATE INDEX idx_original_articles_pinned_time
      ON original_articles(status, is_pinned DESC, pinned_at DESC, published_at DESC, id DESC);
CREATE INDEX idx_original_drafts_author_updated
      ON original_article_drafts(author_id, updated_at DESC);
CREATE INDEX idx_original_drafts_article_author
      ON original_article_drafts(article_id, author_id, updated_at DESC);
CREATE INDEX idx_original_revisions_article_created
      ON original_article_revisions(article_id, created_at DESC);
CREATE INDEX idx_original_assets_article_scope
      ON original_assets(article_id, access_scope, id);
CREATE INDEX idx_original_assets_owner_created
      ON original_assets(owner_id, created_at DESC);
CREATE INDEX idx_original_comments_article_time
      ON original_comments(article_id, status, created_at ASC, id ASC);
CREATE INDEX idx_original_comments_author_time
      ON original_comments(author_id, created_at DESC, id DESC);
CREATE INDEX idx_original_purchases_author_time
      ON original_purchases(author_id, created_at DESC, id DESC);
CREATE INDEX idx_original_reading_history_user_time
      ON original_reading_history(user_id, last_read_at DESC, article_id DESC);
CREATE INDEX idx_original_tags_name ON original_tags(lower(name), id);
CREATE INDEX idx_original_article_tags_tag ON original_article_tags(tag_id, article_id);
CREATE INDEX idx_redemption_codes_batch_status
      ON redemption_codes(batch_id, status, id);
CREATE INDEX idx_search_query_events_time ON search_query_events(created_at);
CREATE INDEX idx_search_query_events_query_time ON search_query_events(query, created_at);
CREATE UNIQUE INDEX idx_search_query_events_event_key ON search_query_events(event_key) WHERE event_key IS NOT NULL;
CREATE INDEX idx_search_query_events_source_time ON search_query_events(source, created_at);
CREATE INDEX idx_search_query_terms_term_event ON search_query_terms(term, search_event_id);
CREATE INDEX idx_search_result_clicks_event_time ON search_result_clicks(search_event_id, clicked_at);
CREATE INDEX idx_search_result_clicks_novel_time ON search_result_clicks(novel_id, clicked_at);
CREATE INDEX idx_station_threads_user_time
      ON station_threads(user_id, last_message_at DESC);
CREATE INDEX idx_station_threads_status_time
      ON station_threads(status, last_message_at DESC);
CREATE INDEX idx_station_messages_thread
      ON station_messages(thread_id, id);
CREATE INDEX idx_telegram_link_tokens_expiry
      ON telegram_link_tokens(expires_at);
CREATE INDEX idx_telegram_message_links_thread
      ON telegram_message_links(station_thread_id, message_id);
CREATE INDEX idx_user_currency_transactions_user_time
      ON user_currency_transactions(user_id, created_at DESC, id DESC);
CREATE UNIQUE INDEX idx_user_currency_transactions_reference
      ON user_currency_transactions(reference_key)
      WHERE reference_key IS NOT NULL;
CREATE INDEX idx_user_entitlements_user_expiry ON user_entitlements(user_id, expires_at, id DESC);
CREATE INDEX idx_user_hidden_tags_user
      ON user_hidden_tags(user_id, tag_id);
CREATE INDEX idx_user_login_records_user_time ON user_login_records(user_id, logged_at);
CREATE INDEX idx_user_login_records_time ON user_login_records(logged_at);
CREATE INDEX idx_user_novel_favorites_user_time
      ON user_novel_favorites(user_id, created_at DESC, novel_id DESC);
CREATE INDEX idx_user_novel_grove_user_time
      ON user_novel_grove(user_id, created_at DESC, novel_id DESC);
CREATE INDEX idx_user_original_author_blocks_user_time
      ON user_original_author_blocks(user_id, created_at DESC, author_id DESC);
CREATE INDEX idx_user_original_favorites_user_time
      ON user_original_favorites(user_id, created_at DESC, article_id DESC);
CREATE INDEX idx_user_original_grove_user_time
      ON user_original_grove(user_id, created_at DESC, article_id DESC);
CREATE INDEX idx_user_read_daily_day
      ON user_read_daily_stats(day DESC, open_count DESC);
CREATE INDEX idx_user_history_novel ON user_reading_history(novel_id);
CREATE INDEX idx_user_history_user_time
     ON user_reading_history(user_id, recorded_in_history, last_read_at DESC);
CREATE INDEX idx_user_sessions_user ON user_sessions(user_id);
CREATE INDEX idx_user_sessions_expires ON user_sessions(expires_at);
CREATE INDEX idx_user_soda_transactions_user_time
      ON user_soda_transactions(user_id, created_at DESC, id DESC);
CREATE INDEX idx_media_assets_kind_created ON media_assets(kind, created_at DESC);
CREATE INDEX idx_media_assets_title ON media_assets(title);
CREATE INDEX idx_media_assets_video_category ON media_assets(kind, category_id, updated_at DESC);
CREATE INDEX idx_media_assets_kind_published ON media_assets(kind, published_at DESC, id DESC);
CREATE INDEX idx_media_assets_kind_content_updated ON media_assets(kind, content_updated_at DESC, id DESC);
CREATE INDEX idx_media_assets_storage_node ON media_assets(storage_node_id, stored_name);
CREATE INDEX idx_analytics_events_time ON analytics_events(created_at);
CREATE INDEX idx_analytics_events_type_time ON analytics_events(event_type, created_at);
CREATE INDEX idx_analytics_events_ip_time ON analytics_events(ip, created_at);
CREATE INDEX idx_analytics_events_path_time ON analytics_events(path, created_at);
CREATE INDEX idx_analytics_events_media_time ON analytics_events(media_id, created_at);
CREATE INDEX idx_analytics_events_tag_time ON analytics_events(tag_id, created_at);
CREATE INDEX idx_content_reports_status_time ON content_reports(status, created_at DESC);
CREATE INDEX idx_content_reports_user_time ON content_reports(user_id, created_at DESC);
CREATE INDEX idx_content_reports_novel_time ON content_reports(novel_id, created_at DESC);
CREATE INDEX idx_content_reports_media_time ON content_reports(media_id, created_at DESC);
CREATE INDEX idx_content_reports_original_time ON content_reports(original_article_id, created_at DESC);
CREATE INDEX idx_media_download_grants_expiry
      ON media_download_grants(expires_at);
CREATE INDEX idx_media_download_sessions_user_time
      ON media_download_sessions(user_id, created_at DESC);
CREATE INDEX idx_media_download_sessions_expiry
      ON media_download_sessions(expires_at);
CREATE INDEX idx_media_playback_grants_expiry
      ON media_playback_grants(expires_at);
CREATE INDEX idx_media_playback_jobs_ready
      ON media_playback_jobs(status, updated_at, media_id);
CREATE INDEX idx_media_prepare_jobs_ready
      ON media_prepare_jobs(status, next_run_at, media_id);
CREATE INDEX idx_media_recommendations_user_time
      ON media_recommendations(user_id, created_at DESC);
CREATE INDEX idx_user_media_favorites_user_time
      ON user_media_favorites(user_id, created_at DESC, media_id DESC);
CREATE INDEX idx_user_media_grove_user_time
      ON user_media_grove(user_id, created_at DESC, media_id DESC);
CREATE INDEX idx_user_media_history_user_time ON user_media_history(user_id, last_accessed_at);
CREATE INDEX idx_user_media_history_media ON user_media_history(media_id);
CREATE INDEX idx_video_playback_sessions_viewer_active
        ON video_playback_sessions(viewer_key, expires_at, last_seen_at);
CREATE INDEX idx_video_playback_sessions_node_active
        ON video_playback_sessions(storage_node_id, expires_at, last_seen_at);
CREATE INDEX idx_video_playback_sessions_expiry
        ON video_playback_sessions(expires_at);
CREATE INDEX idx_video_tags_visible_sort
      ON video_tags(is_visible, sort_order, lower(name), id);
CREATE INDEX idx_media_asset_tags_tag_media
      ON media_asset_tags(tag_id, media_id);
CREATE INDEX idx_media_asset_tags_media_tag
      ON media_asset_tags(media_id, tag_id);
